### ISSUE TITLE
Broken file is Broken

### ISSUE THREAD

**Issue by kajuberdut** [ryanfreckleton/thinkgraph#4]
Using notepad to create a new text file on Windows causes errors when running thinkgraph on said file.

Example:
[break.txt](https://github.com/ryanfreckleton/thinkgraph/files/899808/break.txt)

> C:\Users\pshec\Downloads\thinkgraph-master>thinkgraph break.txt
> Traceback (most recent call last):
>   File "c:\users\pshec\anaconda3\lib\site-packages\grako\contexts.py", line 213, in parse
>     result = rule()
>   File "c:\users\pshec\anaconda3\lib\site-packages\grako\contexts.py", line 61, in wrapper
>     return self._call(rule, name, params, kwparams)
>   File "c:\users\pshec\anaconda3\lib\site-packages\grako\contexts.py", line 469, in _call
>     node, newpos, newstate = self._invoke_rule(rule, name, params, kwparams)
>   File "c:\users\pshec\anaconda3\lib\site-packages\grako\contexts.py", line 509, in _invoke_rule
>     rule(self)
>   File "c:\users\pshec\anaconda3\lib\site-packages\thinkgraph\parser.py", line 69, in _statements_
>     self._check_eof()
>   File "c:\users\pshec\anaconda3\lib\site-packages\grako\contexts.py", line 649, in _check_eof
>     self._error('Expecting end of text.')
>   File "c:\users\pshec\anaconda3\lib\site-packages\grako\contexts.py", line 444, in _error
>     item
> grako.exceptions.FailedParse: (6:1) Expecting end of text. :
> 2 => 3
> ^
> statements
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "c:\users\pshec\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "c:\users\pshec\anaconda3\lib\runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "C:\Users\pshec\Anaconda3\Scripts\thinkgraph.exe\__main__.py", line 9, in <module>
>   File "c:\users\pshec\anaconda3\lib\site-packages\thinkgraph\graph.py", line 70, in main
>     ast = p.parse(f.read(), rule_name="statements", semantics = semantic_graph)
>   File "c:\users\pshec\anaconda3\lib\site-packages\grako\contexts.py", line 221, in parse
>     raise self._furthest_exception
>   File "c:\users\pshec\anaconda3\lib\site-packages\grako\contexts.py", line 469, in _call
>     node, newpos, newstate = self._invoke_rule(rule, name, params, kwparams)
>   File "c:\users\pshec\anaconda3\lib\site-packages\grako\contexts.py", line 509, in _invoke_rule
>     rule(self)
>   File "c:\users\pshec\anaconda3\lib\site-packages\thinkgraph\parser.py", line 150, in _NEWLINE_
>     self._pattern(r'\n')
>   File "c:\users\pshec\anaconda3\lib\site-packages\grako\contexts.py", line 634, in _pattern
>     self._error(pattern, etype=FailedPattern)
>   File "c:\users\pshec\anaconda3\lib\site-packages\grako\contexts.py", line 444, in _error
>     item
> grako.exceptions.FailedPattern: (6:1) expecting '\\n' :
> 
> ^
> NEWLINE
> loop
> statements

**Comment by ryanfreckleton** [comment]
It appears to be related to windows line endings, I'm not sure exactly how to fix this, probably something to do with how grako is configured. I would've hoped that it would use the universal new line feature of Python's regexes, but apparently not.

**Comment by ryanfreckleton** [comment]
Well, a simple regex fix fixes it. :)
